# This is the configuration used to check the rubocop source code.

AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
  Exclude:
    - spec/foodcritic/**/*
    - vendor/**/*

#------------------------------------------------------------------------ lint
Lint/UnusedBlockArgument:
  Enabled: false

#--------------------------------------------------------------------- metrics
Metrics/AbcSize:
  Max: 19

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - each
    - namespace
    - tap

Metrics/LineLength:
  Exclude:
    - 'metadata.rb'

#----------------------------------------------------------------------- style
Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SpaceBeforeFirstArg:
  Enabled: false
